name: Regional CF Official Port Scanner

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scan-ips:
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v5

      - name: 配置 Python 环境
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: 运行扫描脚本
        run: python3 scan.py

      - name: 提交并推送到 GitHub Pages
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add *.txt
          git commit -m "Auto scan completed: $(date +'%Y-%m-%d %H:%M:%S')" || exit 0
          git push
